[package]
name = "biscuit"
version = "0.1.0"
edition = "2021"
authors = ["Chris Yammine <chris@yammine.dev>"]
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.4" }

biscuit-auth = "3.1"

